#!/usr/bin/env sh

set -x
git rev-parse HEAD |
  awk '{
  printf "// Code generated by generate_sha.sh. DO NOT EDIT.\n"
  printf "\n"
  printf "package agent\n\nvar BEARER_SHA=\""$0"\"\n"
  }' >agent_sha.go
