// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.12.3
// source: shape_hash.proto

package interception

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ShapeDescriptor_PrimitiveType int32

const (
	ShapeDescriptor_OBJECT  ShapeDescriptor_PrimitiveType = 0
	ShapeDescriptor_ARRAY   ShapeDescriptor_PrimitiveType = 1
	ShapeDescriptor_STRING  ShapeDescriptor_PrimitiveType = 2
	ShapeDescriptor_NUMBER  ShapeDescriptor_PrimitiveType = 3
	ShapeDescriptor_BOOLEAN ShapeDescriptor_PrimitiveType = 4
	ShapeDescriptor_NULL    ShapeDescriptor_PrimitiveType = 5
)

// Enum value maps for ShapeDescriptor_PrimitiveType.
var (
	ShapeDescriptor_PrimitiveType_name = map[int32]string{
		0: "OBJECT",
		1: "ARRAY",
		2: "STRING",
		3: "NUMBER",
		4: "BOOLEAN",
		5: "NULL",
	}
	ShapeDescriptor_PrimitiveType_value = map[string]int32{
		"OBJECT":  0,
		"ARRAY":   1,
		"STRING":  2,
		"NUMBER":  3,
		"BOOLEAN": 4,
		"NULL":    5,
	}
)

func (x ShapeDescriptor_PrimitiveType) Enum() *ShapeDescriptor_PrimitiveType {
	p := new(ShapeDescriptor_PrimitiveType)
	*p = x
	return p
}

func (x ShapeDescriptor_PrimitiveType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShapeDescriptor_PrimitiveType) Descriptor() protoreflect.EnumDescriptor {
	return file_shape_hash_proto_enumTypes[0].Descriptor()
}

func (ShapeDescriptor_PrimitiveType) Type() protoreflect.EnumType {
	return &file_shape_hash_proto_enumTypes[0]
}

func (x ShapeDescriptor_PrimitiveType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShapeDescriptor_PrimitiveType.Descriptor instead.
func (ShapeDescriptor_PrimitiveType) EnumDescriptor() ([]byte, []int) {
	return file_shape_hash_proto_rawDescGZIP(), []int{1, 0}
}

type FieldDescriptor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash *ShapeDescriptor `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Key  string           `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *FieldDescriptor) Reset() {
	*x = FieldDescriptor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shape_hash_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FieldDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldDescriptor) ProtoMessage() {}

func (x *FieldDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_shape_hash_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldDescriptor.ProtoReflect.Descriptor instead.
func (*FieldDescriptor) Descriptor() ([]byte, []int) {
	return file_shape_hash_proto_rawDescGZIP(), []int{0}
}

func (x *FieldDescriptor) GetHash() *ShapeDescriptor {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *FieldDescriptor) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ShapeDescriptor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Order in schema is used for JSON, while numbers are used for protobuf.
	Fields []*FieldDescriptor            `protobuf:"bytes,4,rep,name=fields,proto3" json:"fields,omitempty"`
	Items  []*ShapeDescriptor            `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	Rules  []string                      `protobuf:"bytes,3,rep,name=rules,proto3" json:"rules,omitempty"`
	Type   ShapeDescriptor_PrimitiveType `protobuf:"varint,1,opt,name=type,proto3,enum=bearer_agent_shape_hash.ShapeDescriptor_PrimitiveType" json:"type,omitempty"`
}

func (x *ShapeDescriptor) Reset() {
	*x = ShapeDescriptor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shape_hash_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShapeDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShapeDescriptor) ProtoMessage() {}

func (x *ShapeDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_shape_hash_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShapeDescriptor.ProtoReflect.Descriptor instead.
func (*ShapeDescriptor) Descriptor() ([]byte, []int) {
	return file_shape_hash_proto_rawDescGZIP(), []int{1}
}

func (x *ShapeDescriptor) GetFields() []*FieldDescriptor {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *ShapeDescriptor) GetItems() []*ShapeDescriptor {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ShapeDescriptor) GetRules() []string {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *ShapeDescriptor) GetType() ShapeDescriptor_PrimitiveType {
	if x != nil {
		return x.Type
	}
	return ShapeDescriptor_OBJECT
}

var File_shape_hash_proto protoreflect.FileDescriptor

var file_shape_hash_proto_rawDesc = []byte{
	0x0a, 0x10, 0x73, 0x68, 0x61, 0x70, 0x65, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x17, 0x62, 0x65, 0x61, 0x72, 0x65, 0x72, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74,
	0x5f, 0x73, 0x68, 0x61, 0x70, 0x65, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x22, 0x61, 0x0a, 0x0f, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x12, 0x3c,
	0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x62,
	0x65, 0x61, 0x72, 0x65, 0x72, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x68, 0x61, 0x70,
	0x65, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x2e, 0x53, 0x68, 0x61, 0x70, 0x65, 0x44, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0xcc,
	0x02, 0x0a, 0x0f, 0x53, 0x68, 0x61, 0x70, 0x65, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x6f, 0x72, 0x12, 0x40, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x28, 0x2e, 0x62, 0x65, 0x61, 0x72, 0x65, 0x72, 0x5f, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x5f, 0x73, 0x68, 0x61, 0x70, 0x65, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x2e, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x52, 0x06, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x73, 0x12, 0x3e, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x62, 0x65, 0x61, 0x72, 0x65, 0x72, 0x5f, 0x61, 0x67, 0x65,
	0x6e, 0x74, 0x5f, 0x73, 0x68, 0x61, 0x70, 0x65, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x2e, 0x53, 0x68,
	0x61, 0x70, 0x65, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x52, 0x05, 0x69,
	0x74, 0x65, 0x6d, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x05, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x12, 0x4a, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x36, 0x2e, 0x62, 0x65, 0x61, 0x72, 0x65,
	0x72, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x68, 0x61, 0x70, 0x65, 0x5f, 0x68, 0x61,
	0x73, 0x68, 0x2e, 0x53, 0x68, 0x61, 0x70, 0x65, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x6f, 0x72, 0x2e, 0x50, 0x72, 0x69, 0x6d, 0x69, 0x74, 0x69, 0x76, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x55, 0x0a, 0x0d, 0x50, 0x72, 0x69, 0x6d, 0x69, 0x74,
	0x69, 0x76, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x4f, 0x42, 0x4a, 0x45, 0x43,
	0x54, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x52, 0x52, 0x41, 0x59, 0x10, 0x01, 0x12, 0x0a,
	0x0a, 0x06, 0x53, 0x54, 0x52, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x55,
	0x4d, 0x42, 0x45, 0x52, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x42, 0x4f, 0x4f, 0x4c, 0x45, 0x41,
	0x4e, 0x10, 0x04, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x55, 0x4c, 0x4c, 0x10, 0x05, 0x42, 0x11, 0x5a,
	0x0f, 0x2e, 0x2e, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x63, 0x65, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_shape_hash_proto_rawDescOnce sync.Once
	file_shape_hash_proto_rawDescData = file_shape_hash_proto_rawDesc
)

func file_shape_hash_proto_rawDescGZIP() []byte {
	file_shape_hash_proto_rawDescOnce.Do(func() {
		file_shape_hash_proto_rawDescData = protoimpl.X.CompressGZIP(file_shape_hash_proto_rawDescData)
	})
	return file_shape_hash_proto_rawDescData
}

var file_shape_hash_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_shape_hash_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_shape_hash_proto_goTypes = []interface{}{
	(ShapeDescriptor_PrimitiveType)(0), // 0: bearer_agent_shape_hash.ShapeDescriptor.PrimitiveType
	(*FieldDescriptor)(nil),            // 1: bearer_agent_shape_hash.FieldDescriptor
	(*ShapeDescriptor)(nil),            // 2: bearer_agent_shape_hash.ShapeDescriptor
}
var file_shape_hash_proto_depIdxs = []int32{
	2, // 0: bearer_agent_shape_hash.FieldDescriptor.hash:type_name -> bearer_agent_shape_hash.ShapeDescriptor
	1, // 1: bearer_agent_shape_hash.ShapeDescriptor.fields:type_name -> bearer_agent_shape_hash.FieldDescriptor
	2, // 2: bearer_agent_shape_hash.ShapeDescriptor.items:type_name -> bearer_agent_shape_hash.ShapeDescriptor
	0, // 3: bearer_agent_shape_hash.ShapeDescriptor.type:type_name -> bearer_agent_shape_hash.ShapeDescriptor.PrimitiveType
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_shape_hash_proto_init() }
func file_shape_hash_proto_init() {
	if File_shape_hash_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_shape_hash_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FieldDescriptor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shape_hash_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShapeDescriptor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_shape_hash_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shape_hash_proto_goTypes,
		DependencyIndexes: file_shape_hash_proto_depIdxs,
		EnumInfos:         file_shape_hash_proto_enumTypes,
		MessageInfos:      file_shape_hash_proto_msgTypes,
	}.Build()
	File_shape_hash_proto = out.File
	file_shape_hash_proto_rawDesc = nil
	file_shape_hash_proto_goTypes = nil
	file_shape_hash_proto_depIdxs = nil
}
