// Code generated by "stringer -type=LogLevel -output data_collection_rules_names.go"; DO NOT EDIT.

package config

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Detected - -1]
	_ = x[Restricted-0]
	_ = x[All-1]
}

const _LogLevel_name = "DetectedRestrictedAll"

var _LogLevel_index = [...]uint8{0, 8, 18, 21}

func (i LogLevel) String() string {
	i -= -1
	if i < 0 || i >= LogLevel(len(_LogLevel_index)-1) {
		return "LogLevel(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _LogLevel_name[_LogLevel_index[i]:_LogLevel_index[i+1]]
}
