// Code generated by "stringer -type=FilterSetOperator -output set_names.go"; DO NOT EDIT.

package filters

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Any-0]
	_ = x[All-1]
	_ = x[NotFirst-2]
}

const _FilterSetOperator_name = "AnyAllNotFirst"

var _FilterSetOperator_index = [...]uint8{0, 3, 6, 14}

func (i FilterSetOperator) String() string {
	if i >= FilterSetOperator(len(_FilterSetOperator_index)-1) {
		return "FilterSetOperator(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FilterSetOperator_name[_FilterSetOperator_index[i]:_FilterSetOperator_index[i+1]]
}
